spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d8ct099o3t8c73e9fj40-a:5432/collegefixitdb
spring.datasource.username=collegefixitdb_user
spring.datasource.password=PN7E3JTHtBTsWKvgsqzpXVICfQrrbPDh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=10000
